"""empty message

Revision ID: 0c32e0bb2115
Revises: 
Create Date: 2022-04-01 23:03:50.440984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c32e0bb2115'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user__stocks', sa.Column('date', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user__stocks', 'date')
    # ### end Alembic commands ###
