"""empty message

Revision ID: 1f976c769906
Revises: 
Create Date: 2022-03-26 17:12:15.798004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f976c769906'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_data', sa.Column('password', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'user_data', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_data', type_='unique')
    op.drop_column('user_data', 'password')
    # ### end Alembic commands ###
