"""empty message

Revision ID: 65346580de7c
Revises: a3f179b560c2
Create Date: 2022-03-29 13:43:58.498843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65346580de7c'
down_revision = 'a3f179b560c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_data', sa.Column('country', sa.String(length=50), nullable=True))
    op.add_column('user_data', sa.Column('city', sa.String(length=50), nullable=True))
    op.drop_column('user_data', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_data', sa.Column('location', sa.VARCHAR(length=50), nullable=True))
    op.drop_column('user_data', 'city')
    op.drop_column('user_data', 'country')
    # ### end Alembic commands ###
